name: mlberrors
channels:
  - defaults
dependencies:
  - backcall=0.1.0
  - binutils_impl_linux-64=2.31.1
  - binutils_linux-64=2.31.1
  - blas=1.0
  - ca-certificates=2019.1.23
  - certifi=2019.3.9
  - cycler=0.10.0
  - dbus=1.13.6
  - decorator=4.4.0
  - expat=2.2.6
  - fontconfig=2.13.0
  - freetype=2.9.1
  - gcc_impl_linux-64=7.3.0
  - gcc_linux-64=7.3.0
  - glib=2.56.2
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - gxx_impl_linux-64=7.3.0
  - gxx_linux-64=7.3.0
  - h5py=2.9.0
  - hdf5=1.10.4
  - icu=58.2
  - intel-openmp=2019.3
  - ipykernel=5.1.0
  - ipython=7.5.0
  - ipython_genutils=0.2.0
  - jedi=0.13.3
  - joblib=0.12.5
  - jpeg=9b
  - jupyter_client=5.2.4
  - jupyter_core=4.4.0
  - kiwisolver=1.1.0
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=8.2.0
  - libgfortran-ng=7.3.0
  - libgpuarray=0.7.6
  - libpng=1.6.37
  - libsodium=1.0.16
  - libstdcxx-ng=8.2.0
  - libuuid=1.0.3
  - libxcb=1.13
  - libxml2=2.9.9
  - mako=1.0.9
  - markupsafe=1.1.1
  - matplotlib=3.0.3
  - mkl=2019.3
  - mkl-service=1.1.2
  - mkl_fft=1.0.12
  - mkl_random=1.0.2
  - ncurses=6.1
  - numpy=1.16.3
  - numpy-base=1.16.3
  - openssl=1.1.1b
  - pandas=0.24.2
  - parso=0.4.0
  - patsy=0.5.1
  - pcre=8.43
  - pexpect=4.7.0
  - pickleshare=0.7.5
  - pip=19.1
  - prompt_toolkit=2.0.9
  - ptyprocess=0.6.0
  - pygments=2.3.1
  - pygpu=0.7.6
  - pymc3=3.6
  - pyparsing=2.4.0
  - pyqt=5.9.2
  - python=3.6.8
  - python-dateutil=2.8.0
  - pytz=2019.1
  - pyzmq=18.0.0
  - qt=5.9.7
  - readline=7.0
  - scipy=1.2.1
  - setuptools=41.0.1
  - sip=4.19.8
  - six=1.12.0
  - sqlite=3.28.0
  - theano=1.0.3
  - tk=8.6.8
  - tornado=6.0.2
  - tqdm=4.31.1
  - traitlets=4.3.2
  - wcwidth=0.1.7
  - wheel=0.33.1
  - xz=5.2.4
  - zeromq=4.3.1
  - zlib=1.2.11

